version: "3.9"

volumes:
    config:

services:
    wop:
        build: .
        volumes:
            - config:/wop/server/data/wop/
        network_mode: "host"
        ports:
            - 27960:27960/udp
